[tool.poetry]
name = "clipboard-server"
version = "0.1.0"
description = ""
authors = ["dd <dmytro.danyliuk@fyst.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
